### ISSUE TITLE
inquiry about supporting all vdj regions

### ISSUE THREAD

**Issue by wbvguo** [algo-cancer/ImmunoTyper-SR#8]
Hi, 

thanks for developing the tool,  may I ask if the current version support all V,D,J regions (or do we plan to support those regions)? Thanks!

Best,

**Comment by michael-ford** [comment]
Hi Wenbin, sorry for the late response. We have version that supports IGLV and TRAV. If you'd like to collaborate and test it out send me an email at fordmk@nih.gov.

**Comment by michael-ford** [comment]
Received your email, closing the issue
