### ISSUE TITLE
GurobiError: Model too large for size-limited license

### ISSUE THREAD

**Issue by wbvguo** [algo-cancer/ImmunoTyper-SR#9]
Dear tool developer,

I give the tool a test run on my bam file, and encounter the following error, have you met such error before? and could you please provide some guidance on how to solve it?

```
Traceback (most recent call last):
  File "xxx/.conda/envs/immunotyper-SR/bin/immunotyper-SR", line 8, in <module>
    sys.exit(main())
  File "xxx/.conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/__main__.py", line 107, in main
    run_immunotyper(args.bam_path, args.ref, args.gene_type, args.hg37, args.output_dir, args.landmark_groups, args.landmarks_per_group, args.max_copy, args.stdev_coeff, args.seq_error_rate, args.write_cache_path, args.solver_time_limit, args.threads)
  File "xxx/.conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/__main__.py", line 169, in run_immunotyper
    model.solve(timeLimit=solver_time_limit*3600, threads=threads, log_path=None)
  File "xxx/.conda/envs/immunotyper-SR/lib/python3.8/site-packages/immunotyper/lpinterface.py", line 167, in solve
    self.model.optimize()
  File "src/gurobipy/model.pxi", line 878, in gurobipy.Model.optimize
gurobipy.GurobiError: Model too large for size-limited license; visit https://www.gurobi.com/free-trial for a full license
```

Thanks,

**Comment by michael-ford** [comment]
Hey Wenbin,

ImmunoTyper-SR uses the Gurobi solver for its ILP model. Looks like you need to get a license as the free trial license it comes with is very limited - they have [free full licenses for academic researchers](https://www.gurobi.com/academia/academic-program-and-licenses/). Once you set that up test it by running `gurobi_cl`. Let me know if you have any problems.

**Comment by wbvguo** [comment]
Thank you, close this issue now

**Comment by didacs** [comment]
Hi @michael-ford,

Is there an alternative to using the Gurobi solver for those of us who don't have access to a free license?

Thank you

**Comment by michael-ford** [comment]
Hi @didacs, currently we only support Gurobi, which provides free academic licenses. We have spent a bit of time implementing Google's MPSolver through OR tools but it is still in alpha and is significantly slower. If you want to open a new issue suggesting this that will help bump it up the priority list.
